version: "3.8"

services:
  frontend:
    image: ghcr.io/caitoor/sort-of-fun-frontend:latest
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.boardgames-frontend.rule=Host(`boardgames.sweavs.de`)"
        - "traefik.http.routers.boardgames-frontend.entrypoints=https"
        - "traefik.http.routers.boardgames-frontend.tls=true"
        - "traefik.http.routers.boardgames-frontend.tls.certresolver=cf"
        - "traefik.http.services.boardgames-frontend.loadbalancer.server.port=80"
        - "traefik.http.services.boardgames-frontend.loadbalancer.server.scheme=http"
    networks:
      - proxy

  backend:
    image: ghcr.io/caitoor/sort-of-fun-backend:latest
    environment:
      - FRONTEND_URL=https://boardgames.sweavs.de
      - MONGO_URI=${MONGO_URI}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
      - BGG_USERNAME=${BGG_USERNAME}
      - PORT=${PORT}
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.boardgames-api.rule=Host(`boardgames-api.sweavs.de`)"
        - "traefik.http.routers.boardgames-api.entrypoints=https"
        - "traefik.http.routers.boardgames-api.tls=true"
        - "traefik.http.routers.boardgames-api.tls.certresolver=cf"
        - "traefik.http.services.boardgames-api.loadbalancer.server.port=3000"
        - "traefik.http.services.boardgames-api.loadbalancer.server.scheme=http"
    networks:
      - proxy
      - boardgames_network

  mongo:
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        failure_action: rollback
        order: start-first
    ports:
      - 27017
    networks:
      - boardgames_network

networks:
  proxy:
    external: true
  boardgames_network:

volumes:
  mongo_data:
